apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: nginx-deployment
spec:
  replicas: 4  # Number of NGINX pods to run
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest  # NGINX container image
          ports:
            - containerPort: 80  # Port the NGINX container listens on
  strategy:
    canary:
      canaryService: auth-svc  # Optional field
      steps:  
        - setWeight: 20
        - pause: 
            duration: "30"
        - setWeight: 80
        - pause: {}
