apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: apache
  namespace: apache-ns
spec:
  template:
    metadata: 
      labels:
        app: apache
    spec:
      containers: 
      - name: apache   
        image: httpd:2.4
  selector:
    matchLabels:
      app: apache
  replicas: 4
  strategy:
    blueGreen: 
      activeService: rollout-bluegreen-active
      previewService: rollout-bluegreen-preview
      autoPromotionEnabled: false
