apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: blue
  namespace: apache-ns
spec:
  template:
    metadata: 
      labels:
        name: blue
    spec:
      containers: 
      - name: blue   
        image: httpd:latest
  selector:
    matchLabels:
      name: blue
  replicas: 4
  strategy:
    blueGreen: 
      activeService: rollout-bluegreen-active
    #  previewService: rollout-bluegreen-preview
      autoPromotionEnabled: false

