apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: blue
  namespace: apache-ns
spec:
  template:
    metadata: 
      labels:
        name: blue
    spec:
      containers: 
      - name: blue   
        image: httpd:latest
  selector:
    matchLabels:
      name: blue
  replicas: 4
  strategy:
    blueGreen: 
      activeService: rollout-bluegreen-active
    #  previewService: rollout-bluegreen-preview
      autoPromotionEnabled: false
-----

apiVersion: v1
kind: Service
metadata:
  name: rollout-bluegreen-active
  namespace: apache-ns
spec:
  selector:
    name: blue
  ports:
    - name: http
      port: 80  # Port exposed by the Service
      targetPort: 80
