apiVersion: v1
kind: Service
metadata:
  name: rollout-bluegreen-active
  namespace: apache-ns
spec:
  selector:
    name: blue
  ports:
    - name: http
      port: 80  # Port exposed by the Service
      targetPort: 80
