# apiVersion: v1
# kind: Service
# metadata:
#   name: rollout-bluegreen-active
#   namespace: apache-ns
# spec:
#   selector:
#      app: apache
#   ports:
#     - name: http
#       port: 80  # Port exposed by the Service
#       targetPort: 80
apiVersion: v1
kind: Service
metadata:
  name: rollout-bluegreen-active
  namespace: apache-ns
spec:
  selector:
    app: apache
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
